// Generated from the live Supabase public schema by `npm run db:types`.
// Do not edit this file manually.

export type Json
  = | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export type Database = {
  public: {
    Tables: {
      clients: {
        Row: {
          id: number
          name: string
          email: string | null
          phone: string | null
          address: string | null
          city: string | null
          postalCode: string | null
          country: string | null
          website: string | null
          notes: string | null
          createdAt: string
          updatedAt: string
          icon: string | null
          description: string | null
          siret: string | null
          status: string
        }
        Insert: {
          id?: never
          name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          postalCode?: string | null
          country?: string | null
          website?: string | null
          notes?: string | null
          createdAt?: string
          updatedAt?: string
          icon?: string | null
          description?: string | null
          siret?: string | null
          status?: string
        }
        Update: {
          id?: never
          name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          postalCode?: string | null
          country?: string | null
          website?: string | null
          notes?: string | null
          createdAt?: string
          updatedAt?: string
          icon?: string | null
          description?: string | null
          siret?: string | null
          status?: string
        }
        Relationships: []
      }
      contacts: {
        Row: {
          id: number
          clientId: number | null
          firstName: string
          lastName: string
          email: string | null
          phone: string | null
          position: string | null
          mobile: string | null
          notes: string | null
          createdAt: string
          updatedAt: string
        }
        Insert: {
          id?: never
          clientId?: number | null
          firstName: string
          lastName: string
          email?: string | null
          phone?: string | null
          position?: string | null
          mobile?: string | null
          notes?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Update: {
          id?: never
          clientId?: number | null
          firstName?: string
          lastName?: string
          email?: string | null
          phone?: string | null
          position?: string | null
          mobile?: string | null
          notes?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Relationships: [
          {
            foreignKeyName: 'contacts_clientId_clients_id_fk'
            columns: ['clientId']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          }
        ]
      }
      documents: {
        Row: {
          id: number
          name: string
          filename: string
          filepath: string
          mimetype: string
          size: number
          entityType: string
          entityId: number
          description: string | null
          createdAt: string
          updatedAt: string
          documentType: string | null
          externalUrl: string | null
        }
        Insert: {
          id?: never
          name: string
          filename: string
          filepath: string
          mimetype: string
          size: number
          entityType: string
          entityId: number
          description?: string | null
          createdAt?: string
          updatedAt?: string
          documentType?: string | null
          externalUrl?: string | null
        }
        Update: {
          id?: never
          name?: string
          filename?: string
          filepath?: string
          mimetype?: string
          size?: number
          entityType?: string
          entityId?: number
          description?: string | null
          createdAt?: string
          updatedAt?: string
          documentType?: string | null
          externalUrl?: string | null
        }
        Relationships: []
      }
      invoices: {
        Row: {
          id: number
          clientId: number
          projectId: number | null
          quoteId: number | null
          number: string
          status: string
          totalHT: number
          totalTTC: number
          vatRate: number
          paidAmount: number
          issueDate: string
          dueDate: string
          paidDate: string | null
          notes: string | null
          terms: string | null
          createdAt: string
          updatedAt: string
        }
        Insert: {
          id?: never
          clientId: number
          projectId?: number | null
          quoteId?: number | null
          number: string
          status?: string
          totalHT?: number
          totalTTC?: number
          vatRate?: number
          paidAmount?: number
          issueDate: string
          dueDate: string
          paidDate?: string | null
          notes?: string | null
          terms?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Update: {
          id?: never
          clientId?: number
          projectId?: number | null
          quoteId?: number | null
          number?: string
          status?: string
          totalHT?: number
          totalTTC?: number
          vatRate?: number
          paidAmount?: number
          issueDate?: string
          dueDate?: string
          paidDate?: string | null
          notes?: string | null
          terms?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Relationships: [
          {
            foreignKeyName: 'invoices_clientId_clients_id_fk'
            columns: ['clientId']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'invoices_projectId_projects_id_fk'
            columns: ['projectId']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'invoices_quoteId_quotes_id_fk'
            columns: ['quoteId']
            isOneToOne: false
            referencedRelation: 'quotes'
            referencedColumns: ['id']
          }
        ]
      }
      payments: {
        Row: {
          id: number
          invoiceId: number
          amount: number
          paymentDate: string
          paymentMethod: string
          type: string
          reference: string | null
          notes: string | null
          createdAt: string
          updatedAt: string
        }
        Insert: {
          id?: never
          invoiceId: number
          amount: number
          paymentDate: string
          paymentMethod: string
          type?: string
          reference?: string | null
          notes?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Update: {
          id?: never
          invoiceId?: number
          amount?: number
          paymentDate?: string
          paymentMethod?: string
          type?: string
          reference?: string | null
          notes?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Relationships: [
          {
            foreignKeyName: 'payments_invoiceId_invoices_id_fk'
            columns: ['invoiceId']
            isOneToOne: false
            referencedRelation: 'invoices'
            referencedColumns: ['id']
          }
        ]
      }
      projects: {
        Row: {
          id: number
          clientId: number
          name: string
          description: string | null
          status: string
          startDate: string | null
          endDate: string | null
          url: string | null
          notes: string | null
          createdAt: string
          updatedAt: string
          links: Json | null
        }
        Insert: {
          id?: never
          clientId: number
          name: string
          description?: string | null
          status?: string
          startDate?: string | null
          endDate?: string | null
          url?: string | null
          notes?: string | null
          createdAt?: string
          updatedAt?: string
          links?: Json | null
        }
        Update: {
          id?: never
          clientId?: number
          name?: string
          description?: string | null
          status?: string
          startDate?: string | null
          endDate?: string | null
          url?: string | null
          notes?: string | null
          createdAt?: string
          updatedAt?: string
          links?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: 'projects_clientId_clients_id_fk'
            columns: ['clientId']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          }
        ]
      }
      quotes: {
        Row: {
          id: number
          clientId: number
          projectId: number | null
          number: string
          status: string
          totalHT: number
          totalTTC: number
          vatRate: number
          issueDate: string
          validUntil: string | null
          notes: string | null
          terms: string | null
          createdAt: string
          updatedAt: string
        }
        Insert: {
          id?: never
          clientId: number
          projectId?: number | null
          number: string
          status?: string
          totalHT?: number
          totalTTC?: number
          vatRate?: number
          issueDate: string
          validUntil?: string | null
          notes?: string | null
          terms?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Update: {
          id?: never
          clientId?: number
          projectId?: number | null
          number?: string
          status?: string
          totalHT?: number
          totalTTC?: number
          vatRate?: number
          issueDate?: string
          validUntil?: string | null
          notes?: string | null
          terms?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Relationships: [
          {
            foreignKeyName: 'quotes_clientId_clients_id_fk'
            columns: ['clientId']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'quotes_projectId_projects_id_fk'
            columns: ['projectId']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      tasks: {
        Row: {
          id: number
          projectId: number | null
          assignedTo: number | null
          title: string
          notes: string | null
          status: string
          priority: string
          dueDate: string | null
          createdAt: string
          updatedAt: string
          workflowTag: string | null
          startedAt: string | null
          completedAt: string | null
        }
        Insert: {
          id?: never
          projectId?: number | null
          assignedTo?: number | null
          title: string
          notes?: string | null
          status?: string
          priority?: string
          dueDate?: string | null
          createdAt?: string
          updatedAt?: string
          workflowTag?: string | null
          startedAt?: string | null
          completedAt?: string | null
        }
        Update: {
          id?: never
          projectId?: number | null
          assignedTo?: number | null
          title?: string
          notes?: string | null
          status?: string
          priority?: string
          dueDate?: string | null
          createdAt?: string
          updatedAt?: string
          workflowTag?: string | null
          startedAt?: string | null
          completedAt?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'tasks_assignedTo_users_id_fk'
            columns: ['assignedTo']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'tasks_projectId_projects_id_fk'
            columns: ['projectId']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      users: {
        Row: {
          id: number
          name: string
          email: string
          role: string
          createdAt: string
          updatedAt: string
        }
        Insert: {
          id?: never
          name: string
          email: string
          role?: string
          createdAt?: string
          updatedAt?: string
        }
        Update: {
          id?: never
          name?: string
          email?: string
          role?: string
          createdAt?: string
          updatedAt?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
